# Generated by Django 4.2.6 on 2023-10-19 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('clientID', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projectName', models.CharField(max_length=150)),
                ('projectId', models.CharField(max_length=20, unique=True)),
                ('projectDescription', models.TextField()),
                ('projectStatus', models.CharField(max_length=20)),
                ('projectStartDate', models.DateField()),
                ('projectFolderNumber', models.CharField(max_length=5)),
                ('projectLink', models.CharField(max_length=1000)),
                ('projectJury', models.CharField(max_length=200)),
                ('assignedTo', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='DjangoProjectManager.client')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=50)),
                ('contactPhone', models.CharField(max_length=20)),
                ('contactEmail', models.CharField(max_length=100)),
                ('contactRole', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='DjangoProjectManager.client')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('done_date', models.DateTimeField(blank=True, null=True)),
                ('done_comment', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='DjangoProjectManager.client')),
                ('done_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='DjangoProjectManager.project')),
            ],
        ),
    ]
