# Generated by Django 4.2.6 on 2023-11-06 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DjangoProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectStartDate',
        ),
        migrations.AlterField(
            model_name='project',
            name='assignedTo',
            field=models.ManyToManyField(default='Teodoro del Castillo', related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
