# Generated by Django 4.2.6 on 2023-11-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectManager', '0002_remove_project_projectstartdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.TextField(default='pruebas'),
        ),
    ]
