# Generated by Django 4.2.6 on 2023-11-06 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DjangoProjectManager', '0005_alter_project_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assignedTo',
            field=models.ManyToManyField(related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
