# Generated by Django 4.2.6 on 2023-11-06 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectManager', '0006_appointment_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='DjangoProjectManager.client'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='DjangoProjectManager.project'),
        ),
    ]
