# Generated by Django 4.2.6 on 2023-11-07 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DjangoProjectManager', '0008_alter_project_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assignedTo',
            field=models.ManyToManyField(default=2, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
