# Generated by Django 4.2.6 on 2023-11-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectManager', '0011_remove_client_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectFolderNumber',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectId',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectJury',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectLink',
            field=models.CharField(default='adelcastillo.com.ar', max_length=1000),
        ),
    ]
