# Generated by Django 4.2.6 on 2023-11-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectManager', '0012_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.TextField(blank=True, default='Completar informacion'),
        ),
    ]
