# Generated by Django 4.2.6 on 2023-11-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectManager', '0013_alter_project_projectdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.TextField(default='Completar informacion'),
        ),
    ]
