# Generated by Django 4.2.6 on 2023-11-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectManager', '0014_alter_project_projectdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='DjangoProjectManager.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished')], default='Active', max_length=20),
        ),
    ]
